setup_heroku: &setup_heroku
  run:
    name: Setup Heroku
    command: |
        chmod +x .circleci/setup-heroku.sh
        .circleci/setup-heroku.sh
deploy_defaults: &deploy_defaults
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - *setup_heroku
    - run:
        name: Build Docker image
        command: docker build -t hy-forum .
    - run:
        name: Publish Docker image to Heroku
        command: |
            echo "$HEROKU_API_KEY" | docker login -username=$HEROKU_USERNAME --password-stdin registry.heroku.com
            docker tag hy-forum registry.heroku.com/hy-forum/web
            docker push registry.heroku.com/hy-forum/web
    - run:
        name: Deploy to Heroku
        command: |
          heroku container:release web --app hy-forum

version: 2.1
executors:
  app-publisher:
    docker:
      - image: olavim/ci-sqitch-heroku:latest

jobs:
  deploy-app:
    executor: app-publisher
    <<: *deploy_defaults
  deploy-database:
    executor: app-publisher
    steps:
      - checkout
      - *setup_heroku
      - run:
          name: Deploy database
          command: |
            cd sqitch
            sqitch target alter remote --uri db:$(heroku config:get DATABASE_URL -a hy-forum)
            sqitch deploy remote

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - deploy-database:
          filters:
            tags:
              only: /^production-.*/
            branches:
              only: /^master$/
      - deploy-app:
          requires:
            - deploy-database
          filters:
            tags:
              only: /^production-.*/
            branches:
              only: /^master$/
