deploy_defaults: &deploy_defaults
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Setup Heroku
        command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
    - run:
        name: Build Docker image
        command: docker build -t hy-forum-$SERVICE services/$SERVICE
    - run:
        name: Publish Docker image to Heroku
        command: |
            echo "$HEROKU_API_KEY" | docker login -username=$HEROKU_USERNAME --password-stdin registry.heroku.com
            docker tag hy-forum-$SERVICE registry.heroku.com/hy-forum-$SERVICE/web
            docker push registry.heroku.com/hy-forum-$SERVICE/web
    - run:
        name: Deploy to Heroku
        command: |
          heroku container:release web --app hy-forum-$SERVICE

version: 2.1
executors:
  frontend-docker-publisher:
    environment:
      SERVICE: frontend
    docker:
      - image: circleci/buildpack-deps:stretch
  backend-docker-publisher:
    environment:
      SERVICE: backend
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  deploy-frontend:
    executor: frontend-docker-publisher
    <<: *deploy_defaults
  deploy-backend:
    executor: backend-docker-publisher
    <<: *deploy_defaults

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - deploy-frontend:
          filters:
            branches:
              only: master
      - deploy-backend:
          filters:
            branches:
              only: master
