"""empty message

Revision ID: 0118e068d022
Revises: 3ef88ca05299
Create Date: 2019-09-22 16:17:33.438414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0118e068d022'
down_revision = '3ef88ca05299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'description')
    # ### end Alembic commands ###
